#pragma once
#include <vector>
#include <list>
#include <array>
#include <unordered_map>
#include <map>
#include <cstring>
#include <glm/glm.hpp>
#include <glm/gtx/string_cast.hpp>
#include <spdlog/spdlog.h>
#include "Utilities/types.hpp"